# Generated by Django 4.2.5 on 2023-11-05 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_booking_no_of_guests_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_guests',
            new_name='No_of_guests',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=None, help_text='Date and time of the reservation', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default=0, help_text='Available quantity of the menu item', validators=[django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
        migrations.AddField(
            model_name='menu',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Price of the menu item', max_digits=10),
        ),
    ]
